[project]
name = "dronetrack"
version = "0.0.1"
description = "Tracking objects using MAVLink"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dronekit==2.9.2",
    "future>=1.0.0",
    "opencv-contrib-python>=4.13.0.92",
]

[tool.uv]
exclude-dependencies = ["opencv-python"]

[tool.uv.sources]
dronekit = { url = "https://github.com/MissouriMRR/docs/raw/refs/heads/main/subteams/flight/installation_guide/dronekit-2.9.2-py310-none-any.whl" }
airsim = { git = "https://github.com/heitmeih/AirSim-fixed-pyinstall.git", subdirectory = "PythonClient" }

[tool.ty.environment]
python = ".venv"

[tool.basedpyright]
typeCheckingMode = "standard"
venvPath = "."
venv = ".venv"


[dependency-groups]
dev = [
    "airsim",
    "dt-apriltags>=3.1.7",
    "onnxruntime>=1.24.2",
    "picamera2>=0.3.34",
    "pre-commit>=4.5.1",
    "ruff>=0.15.9",
    "siyi-sdk>=0.2.12",
    "torchvision>=0.25.0",
]
